import 'backup_execution_config.dart';
import 'backup_routine.dart';

const List<BackupRoutine> defaultBackupRoutines = [
  BackupRoutine(
    id: '1',
    name: 'Documentos de Engenharia',
    sourcePaths: ['/Users/hewerton/Documents/Engineering'],
    destinationPath: '/Volumes/Backup/Engineering',
    scheduleType: ScheduleType.daily,
    scheduleValue: '20:00',
    status: 'Agendado: Diariamente às 20h',
    progress: 0.72,
    type: BackupType.encrypted,
    isCompleted: false,
    executionConfig: BackupExecutionConfig(
      compressionEnabled: true,
      compressionFormat: CompressionFormat.zip,
      encryptionEnabled: true,
      encryptionKeyRef: 'engineering-key',
      retentionCount: 30,
    ),
    lastRunAt: null,
    nextRunAt: null,
  ),
  BackupRoutine(
    id: '2',
    name: 'Fotos da Equipe',
    sourcePaths: ['/Users/hewerton/Pictures/Team'],
    destinationPath: '/Volumes/Backup/TeamPhotos',
    scheduleType: ScheduleType.weekly,
    scheduleValue: 'Sexta 21:00',
    status: 'Último backup: 15/03/2026',
    progress: 1,
    type: BackupType.standard,
    isCompleted: true,
    executionConfig: BackupExecutionConfig(
      compressionEnabled: false,
      compressionFormat: CompressionFormat.zip,
      encryptionEnabled: false,
      retentionCount: 12,
    ),
    lastRunAt: null,
    nextRunAt: null,
  ),
  BackupRoutine(
    id: '3',
    name: 'Projetos CAD',
    sourcePaths: ['/Users/hewerton/Projects/CAD'],
    destinationPath: '/Volumes/Backup/CAD',
    scheduleType: ScheduleType.interval,
    scheduleValue: '30m',
    status: 'Agendado: A cada 30 minutos',
    progress: 0.43,
    type: BackupType.encrypted,
    isCompleted: false,
    executionConfig: BackupExecutionConfig(
      compressionEnabled: true,
      compressionFormat: CompressionFormat.tar,
      encryptionEnabled: true,
      encryptionKeyRef: 'cad-key',
      retentionCount: 48,
    ),
    lastRunAt: null,
    nextRunAt: null,
  ),
  BackupRoutine(
    id: '4',
    name: 'Financeiro',
    sourcePaths: ['/Users/hewerton/Documents/Finance'],
    destinationPath: '/Volumes/Backup/Finance',
    scheduleType: ScheduleType.daily,
    scheduleValue: '18:00',
    status: 'Último backup: 18/02/2026',
    progress: 1,
    type: BackupType.standard,
    isCompleted: true,
    executionConfig: BackupExecutionConfig(
      compressionEnabled: true,
      compressionFormat: CompressionFormat.zip,
      encryptionEnabled: false,
      retentionCount: 20,
    ),
    lastRunAt: null,
    nextRunAt: null,
  ),
];
